e2k_oper elbrus_v1_short_opers [] =
{
{0x00, {{"ANDs", 0},                    {"ANDs", 0},                    {"ANDs", 0}                    }, 0},
{0x01, {{"ANDd", 0},                    {"ANDd", 0},                    {"ANDd", 0}                    }, 0},
{0x02, {{"ANDNs", 0},                   {"ANDNs", 0},                   {"ANDNs", 0}                   }, 0},
{0x03, {{"ANDNd", 0},                   {"ANDNd", 0},                   {"ANDNd", 0}                   }, 0},
{0x04, {{"ORs", 0},                     {"ORs", 0},                     {"ORs", 0}                     }, 0},
{0x05, {{"ORd", 0},                     {"ORd", 0},                     {"ORd", 0}                     }, 0},
{0x06, {{"ORNs", 0},                    {"ORNs", 0},                    {"ORNs", 0}                    }, 0},
{0x07, {{"ORNd", 0},                    {"ORNd", 0},                    {"ORNd", 0}                    }, 0},
{0x08, {{"XORs", 0},                    {"XORs", 0},                    {"XORs", 0}                    }, 0},
{0x09, {{"XORd", 0},                    {"XORd", 0},                    {"XORd", 0}                    }, 0},
{0x0a, {{"XORNs", 0},                   {"XORNs", 0},                   {"XORNs", 0}                   }, 0},
{0x0b, {{"XORNd", 0},                   {"XORNd", 0},                   {"XORNd", 0}                   }, 0},
{0x0c, {{"SXT", 0},                     {"SXT", 0},                     {"SXT", 0}                     }, 0},
{0x0e, {{"MERGEs", 0},                  {"MERGEs", 0},                  {"MERGEs", 0}                  }, 0},
{0x0f, {{"MERGEd", 0},                  {"MERGEd", 0},                  {"MERGEd", 0}                  }, 0},
{0x10, {{"ADDs", 0},                    {"ADDs", 0},                    {"ADDs", 0}                    }, 0},
{0x11, {{"ADDd", 0},                    {"ADDd", 0},                    {"ADDd", 0}                    }, 0},
{0x12, {{"SUBs", 0},                    {"SUBs", 0},                    {"SUBs", 0}                    }, 0},
{0x13, {{"SUBd", 0},                    {"SUBd", 0},                    {"SUBd", 0}                    }, 0},
{0x14, {{"SCLs", 0},                    {"SCLs", 0},                    {"SCLs", 0}                    }, 0},
{0x15, {{"SCLd", 0},                    {"SCLd", 0},                    {"SCLd", 0}                    }, 0},
{0x16, {{"SCRs", 0},                    {"SCRs", 0},                    {"SCRs", 0}                    }, 0},
{0x17, {{"SCRd", 0},                    {"SCRd", 0},                    {"SCRd", 0}                    }, 0},
{0x18, {{"SHLs", 0},                    {"SHLs", 0},                    {"SHLs", 0}                    }, 0},
{0x19, {{"SHLd", 0},                    {"SHLd", 0},                    {"SHLd", 0}                    }, 0},
{0x1a, {{"SHRs", 0},                    {"SHRs", 0},                    {"SHRs", 0}                    }, 0},
{0x1b, {{"SHRd", 0},                    {"SHRd", 0},                    {"SHRd", 0}                    }, 0},
{0x1c, {{"SARs", 0},                    {"SARs", 0},                    {"SARs", 0}                    }, 0},
{0x1d, {{"SARd", 0},                    {"SARd", 0},                    {"SARd", 0}                    }, 0},
{0x1e, {{"GETFs", 0},                   {"GETFs", 0},                   {"GETFs", 0}                   }, 0},
{0x1f, {{"GETFd", 0},                   {"GETFd", 0},                   {"GETFd", 0}                   }, 0},
{0x20, {{"CMPsb", 0},                   {"CMPsb", 0},                   {"", 0}                        }, 0},
{0x21, {{"CMPdb", 0},                   {"CMPdb", 0},                   {"", 0}                        }, 0},
{0x22, {{"CMPANDsb", 0},                {"CMPANDsb", 0},                {"", 0}                        }, 0},
{0x23, {{"CMPANDdb", 0},                {"CMPANDdb", 0},                {"", 0}                        }, 0},
{0x24, {{"CCTOB", 0},                   {"", 0},                        {"STB", 0}                     }, 0},
{0x25, {{"", 0},                        {"", 0},                        {"STH", 0}                     }, 0},
{0x26, {{"", 0},                        {"", 0},                        {"STW", 0}                     }, 0},
{0x27, {{"", 0},                        {"", 0},                        {"STD", 0}                     }, 0},
{0x28, {{"FXCMPsb", 0},                 {"FXCMPsb", 0},                 {"STCSB", 0}                   }, 0},
{0x29, {{"FXCMPdb", 0},                 {"FXCMPdb", 0},                 {"STCSH", 0}                   }, 0},
{0x2a, {{"", 0},                        {"", 0},                        {"STCSW", 0}                   }, 0},
{0x2b, {{"FXCMPxb", 0},                 {"FXCMPxb", 0},                 {"STCSD", 0}                   }, 0},
{0x2c, {{"", 0},                        {"", 0},                        {"STDSB", 0}                   }, 0},
{0x2d, {{"", 0},                        {"", 0},                        {"STDSH", 0}                   }, 0},
{0x2e, {{"FCMPsb", 0},                  {"FCMPsb", 0},                  {"STDSW", 0}                   }, 0},
{0x2f, {{"FCMPdb", 0},                  {"FCMPdb", 0},                  {"STDSD", 0}                   }, 0},
{0x30, {{"FADDs", 0},                   {"FADDs", 0},                   {"STESB", 0}                   }, 0},
{0x31, {{"FADDd", 0},                   {"FADDd", 0},                   {"STESH", 0}                   }, 0},
{0x32, {{"FSUBs", 0},                   {"FSUBs", 0},                   {"STESW", 0}                   }, 0},
{0x33, {{"FSUBd", 0},                   {"FSUBd", 0},                   {"STESD", 0}                   }, 0},
{0x34, {{"FMINs", 0},                   {"FMINs", 0},                   {"STFSB", 0}                   }, 0},
{0x35, {{"FMINd", 0},                   {"FMINd", 0},                   {"STFSH", 0}                   }, 0},
{0x36, {{"FMAXs", 0},                   {"FMAXs", 0},                   {"STFSW", 0}                   }, 0},
{0x37, {{"FMAXd", 0},                   {"FMAXd", 0},                   {"STFSD", 0}                   }, 0},
{0x38, {{"FMULs", 0},                   {"FMULs", 0},                   {"STGSB", 0}                   }, 0},
{0x39, {{"FMULd", 0},                   {"FMULd", 0},                   {"STGSH", 0}                   }, 0},
{0x3a, {{"", 0},                        {"", 0},                        {"STGSW", 0}                   }, 0},
{0x3b, {{"", 0},                        {"", 0},                        {"STGSD", 0}                   }, 0},
{0x3c, {{"FSTOS", 0},                   {"FSTOS", 0},                   {"STSSB", 0}                   }, 0},
{0x3d, {{"FDTOD", 0},                   {"FDTOD", 0},                   {"STSSH", 0}                   }, 0},
{0x3e, {{"FSTOD", 0},                   {"FSTOD", 0},                   {"STSSW", 0}                   }, 0},
{0x3f, {{"FDTOS", 0},                   {"FDTOS", 0},                   {"STSSD", 0}                   }, 0},
{0x40, {{"FXADDss", 0},                 {"FXADDss", 0},                 {"UDIVs", 0}                   }, 0},
{0x41, {{"FXADDdd", 0},                 {"FXADDdd", 0},                 {"UDIVd", 0}                   }, 0},
{0x42, {{"FXADDsx", 0},                 {"FXADDsx", 0},                 {"SDIVs", 0}                   }, 0},
{0x43, {{"FXADDdx", 0},                 {"FXADDdx", 0},                 {"SDIVd", 0}                   }, 0},
{0x44, {{"FXADDxs", 0},                 {"FXADDxs", 0},                 {"UDIVX", 0}                   }, 0},
{0x45, {{"FXADDxd", 0},                 {"FXADDxd", 0},                 {"UMODX", 0}                   }, 0},
{0x46, {{"", 0},                        {"", 0},                        {"SDIVX", 0}                   }, 0},
{0x47, {{"FXADDxx", 0},                 {"FXADDxx", 0},                 {"SMODX", 0}                   }, 0},
{0x48, {{"FXSUBss", 0},                 {"FXSUBss", 0},                 {"FXDIVss", 0}                 }, 0},
{0x49, {{"FXSUBdd", 0},                 {"FXSUBdd", 0},                 {"FXDIVdd", 0}                 }, 0},
{0x4a, {{"FXSUBsx", 0},                 {"FXSUBsx", 0},                 {"FXDIVsx", 0}                 }, 0},
{0x4b, {{"FXSUBdx", 0},                 {"FXSUBdx", 0},                 {"FXDIVdx", 0}                 }, 0},
{0x4c, {{"FXSUBxs", 0},                 {"FXSUBxs", 0},                 {"FXDIVxs", 0}                 }, 0},
{0x4d, {{"FXSUBxd", 0},                 {"FXSUBxd", 0},                 {"FXDIVxd", 0}                 }, 0},
{0x4f, {{"FXSUBxx", 0},                 {"FXSUBxx", 0},                 {"FXDIVxx", 0}                 }, 0},
{0x50, {{"FXMULss", 0},                 {"FXMULss", 0},                 {"", 0}                        }, 0},
{0x51, {{"FXMULdd", 0},                 {"FXMULdd", 0},                 {"", 0}                        }, 0},
{0x52, {{"FXMULsx", 0},                 {"FXMULsx", 0},                 {"FXSQRTIsx", 0}               }, 0},
{0x53, {{"FXMULdx", 0},                 {"FXMULdx", 0},                 {"FXSQRTIdx", 0}               }, 0},
{0x54, {{"FXMULxs", 0},                 {"FXMULxs", 0},                 {"", 0}                        }, 0},
{0x55, {{"FXMULxd", 0},                 {"FXMULxd", 0},                 {"", 0}                        }, 0},
{0x57, {{"FXMULxx", 0},                 {"FXMULxx", 0},                 {"FXSQRTIxx", 0}               }, 0},
{0x58, {{"FXRSUBss", 0},                {"FXRSUBss", 0},                {"", 0}                        }, 0},
{0x59, {{"FXRSUBdd", 0},                {"FXRSUBdd", 0},                {"FXSQRTUxx", 0}               }, 0},
{0x5a, {{"FXRSUBsx", 0},                {"FXRSUBsx", 0},                {"FXSQRTUsx", 0}               }, 0},
{0x5b, {{"FXRSUBdx", 0},                {"FXRSUBdx", 0},                {"FXSQRTUdx", 0}               }, 0},
{0x5c, {{"", 0},                        {"MOVFI", 0},                   {"", 0}                        }, 0},
{0x5d, {{"", 0},                        {"", 0},                        {"FXSQRTTxx", 0}               }, 0},
{0x5e, {{"", 0},                        {"MOVIF", 0},                   {"FXSQRTTsx", 0}               }, 0},
{0x5f, {{"", 0},                        {"", 0},                        {"FXSQRTTdx", 0}               }, 0},
{0x60, {{"MOVTs", 0},                   {"MOVTs", 0},                   {"FXDIVTss", 0}                }, 0},
{0x61, {{"MOVTd", 0},                   {"MOVTd", 0},                   {"FXDIVTdd", 0}                }, 0},
{0x62, {{"DRTOAP", 0},                  {"DRTOAP", 0},                  {"FXDIVTsx", 0}                }, 0},
{0x63, {{"GETPL", 0},                   {"VFSI", 0},                    {"FXDIVTdx", 0}                }, 0},
{0x64, {{"LDB", 0},                     {"", 0},                        {"LDB", 0}                     }, 0},
{0x65, {{"LDH", 0},                     {"", 0},                        {"LDH", 0}                     }, 0},
{0x66, {{"LDW", 0},                     {"", 0},                        {"LDW", 0}                     }, 0},
{0x67, {{"LDD", 0},                     {"", 0},                        {"LDD", 0}                     }, 0},
{0x68, {{"LDCSB", 0},                   {"", 0},                        {"LDCSB", 0}                   }, 0},
{0x69, {{"LDCSH", 0},                   {"", 0},                        {"LDCSH", 0}                   }, 0},
{0x6a, {{"LDCSW", 0},                   {"", 0},                        {"LDCSW", 0}                   }, 0},
{0x6b, {{"LDCSD", 0},                   {"", 0},                        {"LDCSD", 0}                   }, 0},
{0x6c, {{"LDDSB", 0},                   {"", 0},                        {"LDDSB", 0}                   }, 0},
{0x6d, {{"LDDSH", 0},                   {"", 0},                        {"LDDSH", 0}                   }, 0},
{0x6e, {{"LDDSW", 0},                   {"", 0},                        {"LDDSW", 0}                   }, 0},
{0x6f, {{"LDDSD", 0},                   {"", 0},                        {"LDDSD", 0}                   }, 0},
{0x70, {{"LDESB", 0},                   {"", 0},                        {"LDESB", 0}                   }, 0},
{0x71, {{"LDESH", 0},                   {"", 0},                        {"LDESH", 0}                   }, 0},
{0x72, {{"LDESW", 0},                   {"", 0},                        {"LDESW", 0}                   }, 0},
{0x73, {{"LDESD", 0},                   {"", 0},                        {"LDESD", 0}                   }, 0},
{0x74, {{"LDFSB", 0},                   {"", 0},                        {"LDFSB", 0}                   }, 0},
{0x75, {{"LDFSH", 0},                   {"", 0},                        {"LDFSH", 0}                   }, 0},
{0x76, {{"LDFSW", 0},                   {"", 0},                        {"LDFSW", 0}                   }, 0},
{0x77, {{"LDFSD", 0},                   {"", 0},                        {"LDFSD", 0}                   }, 0},
{0x78, {{"LDGSB", 0},                   {"", 0},                        {"LDGSB", 0}                   }, 0},
{0x79, {{"LDGSH", 0},                   {"", 0},                        {"LDGSH", 0}                   }, 0},
{0x7a, {{"LDGSW", 0},                   {"", 0},                        {"LDGSW", 0}                   }, 0},
{0x7b, {{"LDGSD", 0},                   {"", 0},                        {"LDGSD", 0}                   }, 0},
{0x7c, {{"LDSSB", 0},                   {"", 0},                        {"LDSSB", 0}                   }, 0},
{0x7d, {{"LDSSH", 0},                   {"", 0},                        {"LDSSH", 0}                   }, 0},
{0x7e, {{"LDSSW", 0},                   {"", 0},                        {"LDSSW", 0}                   }, 0},
{0x7f, {{"LDSSD", 0},                   {"", 0},                        {"LDSSD", 0}                   }, 0},
};

e2k_oper elbrus_v2_short_opers [] =
{
{0x26, {{"BITREVs", 0},                 {"BITREVs", 0},                 {"", 0}                        }, 0},
{0x27, {{"BITREVd", 0},                 {"BITREVd", 0},                 {"", 0}                        }, 0},
{0x5c, {{"MOVFI", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x5e, {{"MOVIF", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x5f, {{"MOVX", 0},                    {"MOVX", 0},                    {"", 0}                        }, 0},
{0x64, {{"", 0},                        {"LZCNTs", 0},                  {"", 0}                        }, 0},
{0x65, {{"", 0},                        {"LZCNTd", 0},                  {"", 0}                        }, 0},
{0x66, {{"", 0},                        {"POPCNTs", 0},                 {"", 0}                        }, 0},
{0x67, {{"", 0},                        {"POPCNTd", 0},                 {"", 0}                        }, 0},
};

e2k_oper elbrus_v3_short_opers [] =
{
};

e2k_oper elbrus_v4_short_opers [] =
{
};

e2k_oper elbrus_v5_short_opers [] =
{
};

e2k_oper elbrus_v6_short_opers [] =
{
{0x68, {{"", 0},                        {"VFBGV", 0},                   {"", 0}                        }, 0},
{0x69, {{"", 0},                        {"MODBGV", 0},                  {"", 0}                        }, 0},
{0x6a, {{"", 0},                        {"MKFSW", 0},                   {"", 0}                        }, 0},
};

e2k_oper elbrus_v1_long_opers [] =
{
{0x00, {{"PMINUB", 0},                  {"PUNPCKHBH", 0},               {"", 0}                        }, 0},
{0x01, {{"PMINSH", 0},                  {"PUNPCKLBH", 0},               {"", 0}                        }, 0},
{0x02, {{"PMAXUB", 0},                  {"PUNPCKHHW", 0},               {"STCSQ", 0}                   }, 0},
{0x03, {{"PMAXSH", 0},                  {"PUNPCKLHW", 0},               {"STDSQ", 0}                   }, 0},
{0x04, {{"", 0},                        {"PUNPCKHWD", 0},               {"STESQ", 0}                   }, 0},
{0x05, {{"", 0},                        {"PUNPCKLWD", 0},               {"STFSQ", 0}                   }, 0},
{0x06, {{"", 0},                        {"PMOVMSKPS", 0},               {"STGSQ", 0}                   }, 0},
{0x07, {{"", 0},                        {"PMOVMSKPD", 0},               {"STSSQ", 0}                   }, 0},
{0x08, {{"PADDB", 0},                   {"PACKSSHB", 0},                {"GETTAGs", 0}                 }, 0},
{0x09, {{"PADDH", 0},                   {"PACKUSHB", 0},                {"GETTAGd", 0}                 }, 0},
{0x0a, {{"PADDSB", 0},                  {"PACKSSWH", 0},                {"PUTTAGs", 0}                 }, 0},
{0x0b, {{"PADDSH", 0},                  {"PMOVMSKB", 0},                {"PUTTAGd", 0}                 }, 0},
{0x0c, {{"PADDUSB", 0},                 {"PSRLQH", 0},                  {"", 0}                        }, 0},
{0x0d, {{"PADDUSH", 0},                 {"PSRLQL", 0},                  {"", 0}                        }, 0},
{0x0e, {{"PADDW", 0},                   {"PSLLQH", 0},                  {"", 0}                        }, 0},
{0x0f, {{"PADDD", 0},                   {"PSLLQL", 0},                  {"", 0}                        }, 0},
{0x10, {{"PSUBB", 0},                   {"PSRLW", 0},                   {"", 0}                        }, 0},
{0x11, {{"PSUBH", 0},                   {"PSRLH", 0},                   {"", 0}                        }, 0},
{0x12, {{"PSUBSB", 0},                  {"PSRAW", 0},                   {"", 0}                        }, 0},
{0x13, {{"PSUBSH", 0},                  {"PSRAH", 0},                   {"", 0}                        }, 0},
{0x14, {{"PSUBUSB", 0},                 {"PSLLW", 0},                   {"", 0}                        }, 0},
{0x15, {{"PSUBUSH", 0},                 {"PSLLH", 0},                   {"", 0}                        }, 0},
{0x16, {{"PSUBW", 0},                   {"PSHUFW", 0},                  {"", 0}                        }, 0},
{0x17, {{"PSUBD", 0},                   {"PSHUFH", 0},                  {"", 0}                        }, 0},
{0x18, {{"PCMPEQB", 0},                 {"PMULHH", 0},                  {"", 0}                        }, 0},
{0x19, {{"PCMPEQH", 0},                 {"PMULLH", 0},                  {"", 0}                        }, 0},
{0x1a, {{"PCMPEQW", 0},                 {"PMADDH", 0},                  {"", 0}                        }, 0},
{0x1b, {{"PCMPGTB", 0},                 {"PMULHUH", 0},                 {"STRD", 0}                    }, 0},
{0x1c, {{"PCMPGTH", 0},                 {"PSADBW", 0},                  {"STAAB", 0}                   }, 0},
{0x1d, {{"PCMPGTW", 0},                 {"", 0},                        {"STAAH", 0}                   }, 0},
{0x1e, {{"PAVGUSB", 0},                 {"PEXTRH", 0},                  {"STAAW", 0}                   }, 0},
{0x1f, {{"PAVGUSH", 0},                 {"PINSH", 0},                   {"STAAD", 0}                   }, 0},
{0x20, {{"MULs", 0},                    {"MULs", 0},                    {"", 0}                        }, 0},
{0x21, {{"MULd", 0},                    {"MULd", 0},                    {"", 0}                        }, 0},
{0x22, {{"UMULX", 0},                   {"UMULX", 0},                   {"", 0}                        }, 0},
{0x23, {{"SMULX", 0},                   {"SMULX", 0},                   {"", 0}                        }, 0},
{0x24, {{"", 0},                        {"", 0},                        {"STGDB", 0}                   }, 0},
{0x25, {{"", 0},                        {"", 0},                        {"STGDH", 0}                   }, 0},
{0x26, {{"INVTC", 0},                   {"", 0},                        {"STGDW", 0}                   }, 0},
{0x27, {{"", 0},                        {"", 0},                        {"STGDD", 0}                   }, 0},
{0x28, {{"FXCMPsf", 0},                 {"FXCMPsf", 0},                 {"STAPB", 0}                   }, 0},
{0x29, {{"FXCMPdf", 0},                 {"FXCMPdf", 0},                 {"STAPH", 0}                   }, 0},
{0x2a, {{"", 0},                        {"", 0},                        {"STAPW", 0}                   }, 0},
{0x2b, {{"FXCMPxf", 0},                 {"FXCMPxf", 0},                 {"STAPD", 0}                   }, 0},
{0x2c, {{"FCMPs", 0},                   {"FCMPs", 0},                   {"", 0}                        }, 0},
{0x2d, {{"FCMPd", 0},                   {"FCMPd", 0},                   {"", 0}                        }, 0},
{0x2e, {{"FCMPsf", 0},                  {"FCMPsf", 0},                  {"", 0}                        }, 0},
{0x2f, {{"FCMPdf", 0},                  {"FCMPdf", 0},                  {"", 0}                        }, 0},
{0x30, {{"PFADDs", 0},                  {"PFADDs", 0},                  {"", 0}                        }, 0},
{0x31, {{"PFADDd", 0},                  {"PFADDd", 0},                  {"", 0}                        }, 0},
{0x32, {{"PFSUBs", 0},                  {"PFSUBs", 0},                  {"", 0}                        }, 0},
{0x33, {{"PFSUBd", 0},                  {"PFSUBd", 0},                  {"", 0}                        }, 0},
{0x34, {{"PFMINs", 0},                  {"PFMINs", 0},                  {"", 0}                        }, 0},
{0x35, {{"PFMINd", 0},                  {"PFMINd", 0},                  {"", 0}                        }, 0},
{0x36, {{"PFMAXs", 0},                  {"PFMAXs", 0},                  {"", 0}                        }, 0},
{0x37, {{"PFMAXd", 0},                  {"PFMAXd", 0},                  {"", 0}                        }, 0},
{0x38, {{"PFMULs", 0},                  {"PFMULs", 0},                  {"", 0}                        }, 0},
{0x39, {{"PFMULd", 0},                  {"PFMULd", 0},                  {"STGDQ", 0}                   }, 0},
{0x3a, {{"PFCMPs", 0},                  {"PFCMPs", 0},                  {"STAPQ", 0}                   }, 0},
{0x3b, {{"PFCMPd", 0},                  {"PFCMPd", 0},                  {"", 0}                        }, 0},
{0x3c, {{"RWs", 0},                     {"", 0},                        {"", 0}                        }, 0},
{0x3d, {{"RWd", 0},                     {"", 0},                        {"", 0}                        }, 0},
{0x3e, {{"RRs", 0},                     {"", 0},                        {"", 0}                        }, 0},
{0x3f, {{"RRd", 0},                     {"", 0},                        {"STAAQ", 0}                   }, 0},
{0x42, {{"LDCSQ", 0},                   {"", 0},                        {"LDCSQ", 0}                   }, 0},
{0x43, {{"LDDSQ", 0},                   {"", 0},                        {"LDDSQ", 0}                   }, 0},
{0x44, {{"LDESQ", 0},                   {"", 0},                        {"LDESQ", 0}                   }, 0},
{0x45, {{"LDFSQ", 0},                   {"", 0},                        {"LDFSQ", 0}                   }, 0},
{0x46, {{"LDGSQ", 0},                   {"", 0},                        {"LDGSQ", 0}                   }, 0},
{0x47, {{"LDSSQ", 0},                   {"", 0},                        {"LDSSQ", 0}                   }, 0},
{0x48, {{"PANDd", 0},                   {"PANDd", 0},                   {"FDIVs", 0}                   }, 0},
{0x49, {{"PANDNd", 0},                  {"PANDNd", 0},                  {"FDIVd", 0}                   }, 0},
{0x4a, {{"PORd", 0},                    {"PORd", 0},                    {"PFDIVs", 0}                  }, 0},
{0x4b, {{"PXORd", 0},                   {"PXORd", 0},                   {"PFDIVd", 0}                  }, 0},
{0x4c, {{"", 0},                        {"PSRLD", 0},                   {"FSQRTs", 0}                  }, 0},
{0x4d, {{"", 0},                        {"", 0},                        {"FSQRTId", 0}                 }, 0},
{0x4e, {{"", 0},                        {"PSLLD", 0},                   {"PFSQRTs", 0}                 }, 0},
{0x50, {{"APTOAP", 0},                  {"APTOAP", 0},                  {"FRCPs", 0}                   }, 0},
{0x51, {{"APTOAPB", 0},                 {"APTOAPB", 0},                 {"FSQRTTd", 0}                 }, 0},
{0x52, {{"GETVA", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x53, {{"", 0},                        {"", 0},                        {"PFSQRTTd", 0}                }, 0},
{0x54, {{"", 0},                        {"", 0},                        {"FRSQRTs", 0}                 }, 0},
{0x57, {{"MOVTq", 0},                   {"MOVTq", 0},                   {"", 0}                        }, 0},
{0x58, {{"GETSP", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x5b, {{"LDRD", 0},                    {"", 0},                        {"LDRD", 0}                    }, 0},
{0x5c, {{"", 0},                        {"", 0},                        {"LDAAB", 0}                   }, 0},
{0x5d, {{"", 0},                        {"", 0},                        {"LDAAH", 0}                   }, 0},
{0x5e, {{"", 0},                        {"", 0},                        {"LDAAW", 0}                   }, 0},
{0x5f, {{"", 0},                        {"", 0},                        {"LDAAD", 0}                   }, 0},
{0x60, {{"LDCUDB", 0},                  {"", 0},                        {"LDCUDB", 0}                  }, 0},
{0x61, {{"LDCUDH", 0},                  {"", 0},                        {"LDCUDH", 0}                  }, 0},
{0x62, {{"LDCUDW", 0},                  {"", 0},                        {"LDCUDW", 0}                  }, 0},
{0x63, {{"LDCUDD", 0},                  {"", 0},                        {"LDCUDD", 0}                  }, 0},
{0x64, {{"LDGDB", 0},                   {"", 0},                        {"LDGDB", 0}                   }, 0},
{0x65, {{"LDGDH", 0},                   {"", 0},                        {"LDGDH", 0}                   }, 0},
{0x66, {{"LDGDW", 0},                   {"", 0},                        {"LDGDW", 0}                   }, 0},
{0x67, {{"LDGDD", 0},                   {"", 0},                        {"LDGDD", 0}                   }, 0},
{0x68, {{"LDAPB", 0},                   {"", 0},                        {"LDAPB", 0}                   }, 0},
{0x69, {{"LDAPH", 0},                   {"", 0},                        {"LDAPH", 0}                   }, 0},
{0x6a, {{"LDAPW", 0},                   {"", 0},                        {"LDAPW", 0}                   }, 0},
{0x6b, {{"LDAPD", 0},                   {"", 0},                        {"LDAPD", 0}                   }, 0},
{0x78, {{"LDCUDQ", 0},                  {"", 0},                        {"LDCUDQ", 0}                  }, 0},
{0x79, {{"LDGDQ", 0},                   {"", 0},                        {"LDGDQ", 0}                   }, 0},
{0x7a, {{"LDAPQ", 0},                   {"", 0},                        {"LDAPQ", 0}                   }, 0},
{0x7f, {{"", 0},                        {"", 0},                        {"LDAAQ", 0}                   }, 0},
{0x24, {{"GETTC", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x25, {{"PUTTC", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x2c, {{"", 0},                        {"", 0},                        {"STODRB", 0}                  }, 1},
{0x2d, {{"", 0},                        {"", 0},                        {"STODRH", 0}                  }, 1},
{0x2e, {{"", 0},                        {"", 0},                        {"STODRW", 0}                  }, 1},
{0x2f, {{"", 0},                        {"", 0},                        {"STODRD", 0}                  }, 1},
{0x30, {{"", 0},                        {"", 0},                        {"STODWB", 0}                  }, 1},
{0x31, {{"", 0},                        {"", 0},                        {"STODWH", 0}                  }, 1},
{0x32, {{"", 0},                        {"", 0},                        {"STODWW", 0}                  }, 1},
{0x33, {{"", 0},                        {"", 0},                        {"STODWD", 0}                  }, 1},
{0x34, {{"", 0},                        {"", 0},                        {"STODPB", 0}                  }, 1},
{0x35, {{"", 0},                        {"", 0},                        {"STODPH", 0}                  }, 1},
{0x36, {{"", 0},                        {"", 0},                        {"STODPW", 0}                  }, 1},
{0x37, {{"", 0},                        {"", 0},                        {"STODPD", 0}                  }, 1},
{0x3b, {{"", 0},                        {"", 0},                        {"STODRQ", 0}                  }, 1},
{0x3c, {{"", 0},                        {"", 0},                        {"STODWQ", 0}                  }, 1},
{0x3d, {{"", 0},                        {"", 0},                        {"STODPQ", 0}                  }, 1},
{0x53, {{"TDTOMP", 0},                  {"TDTOMP", 0},                  {"", 0}                        }, 1},
{0x54, {{"ODTOAP", 0},                  {"ODTOAP", 0},                  {"", 0}                        }, 1},
{0x55, {{"CAST", 0},                    {"CAST", 0},                    {"", 0}                        }, 1},
{0x56, {{"GETTD", 0},                   {"", 0},                        {"", 0}                        }, 1},
{0x5a, {{"GETSOD", 0},                  {"GETSOD", 0},                  {"", 0}                        }, 1},
{0x6c, {{"LDODRB", 0},                  {"", 0},                        {"LDODRB", 0}                  }, 1},
{0x6d, {{"LDODRH", 0},                  {"", 0},                        {"LDODRH", 0}                  }, 1},
{0x6e, {{"LDODRW", 0},                  {"", 0},                        {"LDODRW", 0}                  }, 1},
{0x6f, {{"LDODRD", 0},                  {"", 0},                        {"LDODRD", 0}                  }, 1},
{0x70, {{"LDODWB", 0},                  {"", 0},                        {"LDODWB", 0}                  }, 1},
{0x71, {{"LDODWH", 0},                  {"", 0},                        {"LDODWH", 0}                  }, 1},
{0x72, {{"LDODWW", 0},                  {"", 0},                        {"LDODWW", 0}                  }, 1},
{0x73, {{"LDODWD", 0},                  {"", 0},                        {"LDODWD", 0}                  }, 1},
{0x74, {{"LDODPB", 0},                  {"", 0},                        {"LDODPB", 0}                  }, 1},
{0x75, {{"LDODPH", 0},                  {"", 0},                        {"LDODPH", 0}                  }, 1},
{0x76, {{"LDODPW", 0},                  {"", 0},                        {"LDODPW", 0}                  }, 1},
{0x77, {{"LDODPD", 0},                  {"", 0},                        {"LDODPD", 0}                  }, 1},
{0x7b, {{"LDODRQ", 0},                  {"", 0},                        {"LDODRQ", 0}                  }, 1},
{0x7c, {{"LDODWQ", 0},                  {"", 0},                        {"LDODWQ", 0}                  }, 1},
{0x7d, {{"LDODPQ", 0},                  {"", 0},                        {"LDODPQ", 0}                  }, 1},
};

e2k_oper elbrus_v2_long_opers [] =
{
{0x1d, {{"", 0},                        {"PMULUBHH", 0},                {"", 0}                        }, 0},
{0x2c, {{"", 0},                        {"", 0},                        {"STODRB", 0}                  }, 1},
{0x2d, {{"", 0},                        {"", 0},                        {"STODRH", 0}                  }, 1},
{0x2e, {{"", 0},                        {"", 0},                        {"STODRW", 0}                  }, 1},
{0x2f, {{"", 0},                        {"", 0},                        {"STODRD", 0}                  }, 1},
{0x30, {{"", 0},                        {"", 0},                        {"STODWB", 0}                  }, 1},
{0x31, {{"", 0},                        {"", 0},                        {"STODWH", 0}                  }, 1},
{0x32, {{"", 0},                        {"", 0},                        {"STODWW", 0}                  }, 1},
{0x33, {{"", 0},                        {"", 0},                        {"STODWD", 0}                  }, 1},
{0x34, {{"", 0},                        {"", 0},                        {"STODPB", 0}                  }, 1},
{0x35, {{"", 0},                        {"", 0},                        {"STODPH", 0}                  }, 1},
{0x36, {{"", 0},                        {"", 0},                        {"STODPW", 0}                  }, 1},
{0x37, {{"", 0},                        {"", 0},                        {"STODPD", 0}                  }, 1},
{0x3b, {{"", 0},                        {"", 0},                        {"STODRQ", 0}                  }, 1},
{0x3c, {{"", 0},                        {"", 0},                        {"STODWQ", 0}                  }, 1},
{0x3d, {{"", 0},                        {"", 0},                        {"STODPQ", 0}                  }, 1},
{0x53, {{"TDTOMP", 0},                  {"TDTOMP", 0},                  {"", 0}                        }, 1},
{0x54, {{"ODTOAP", 0},                  {"ODTOAP", 0},                  {"", 0}                        }, 1},
{0x55, {{"CAST", 0},                    {"CAST", 0},                    {"", 0}                        }, 1},
{0x56, {{"GETTD", 0},                   {"", 0},                        {"", 0}                        }, 1},
{0x5a, {{"GETSOD", 0},                  {"GETSOD", 0},                  {"", 0}                        }, 1},
{0x6c, {{"LDODRB", 0},                  {"", 0},                        {"LDODRB", 0}                  }, 1},
{0x6d, {{"LDODRH", 0},                  {"", 0},                        {"LDODRH", 0}                  }, 1},
{0x6e, {{"LDODRW", 0},                  {"", 0},                        {"LDODRW", 0}                  }, 1},
{0x6f, {{"LDODRD", 0},                  {"", 0},                        {"LDODRD", 0}                  }, 1},
{0x70, {{"LDODWB", 0},                  {"", 0},                        {"LDODWB", 0}                  }, 1},
{0x71, {{"LDODWH", 0},                  {"", 0},                        {"LDODWH", 0}                  }, 1},
{0x72, {{"LDODWW", 0},                  {"", 0},                        {"LDODWW", 0}                  }, 1},
{0x73, {{"LDODWD", 0},                  {"", 0},                        {"LDODWD", 0}                  }, 1},
{0x74, {{"LDODPB", 0},                  {"", 0},                        {"LDODPB", 0}                  }, 1},
{0x75, {{"LDODPH", 0},                  {"", 0},                        {"LDODPH", 0}                  }, 1},
{0x76, {{"LDODPW", 0},                  {"", 0},                        {"LDODPW", 0}                  }, 1},
{0x77, {{"LDODPD", 0},                  {"", 0},                        {"LDODPD", 0}                  }, 1},
{0x7b, {{"LDODRQ", 0},                  {"", 0},                        {"LDODRQ", 0}                  }, 1},
{0x7c, {{"LDODWQ", 0},                  {"", 0},                        {"LDODWQ", 0}                  }, 1},
{0x7d, {{"LDODPQ", 0},                  {"", 0},                        {"LDODPQ", 0}                  }, 1},
};

e2k_oper elbrus_v3_long_opers [] =
{
{0x04, {{"PMINSB", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x05, {{"PMINUH", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x06, {{"PMAXSB", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x07, {{"PMAXUH", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x24, {{"GETTST", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x25, {{"PUTTST", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x4d, {{"PCMPEQD", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x4f, {{"PCMPGTD", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x58, {{"", 0},                        {"MPSADBH", 0},                 {"", 0}                        }, 0},
{0x68, {{"", 0},                        {"PMADDUBSH", 0},               {"", 0}                        }, 0},
{0x69, {{"", 0},                        {"PMULHRSH", 0},                {"", 0}                        }, 0},
{0x6a, {{"", 0},                        {"PHMINPOSUH", 0},              {"", 0}                        }, 0},
{0x6b, {{"", 0},                        {"PACKUSWH", 0},                {"", 0}                        }, 0},
{0x6c, {{"FSTOIFs", 0},                 {"FSTOIFs", 0},                 {"", 0}                        }, 0},
{0x6d, {{"FDTOIFd", 0},                 {"FDTOIFd", 0},                 {"", 0}                        }, 0},
{0x6e, {{"PFSTOIFs", 0},                {"PFSTOIFs", 0},                {"", 0}                        }, 0},
{0x6f, {{"PFDTOIFd", 0},                {"PFDTOIFd", 0},                {"", 0}                        }, 0},
{0x70, {{"UMULHd", 0},                  {"UMULHd", 0},                  {"", 0}                        }, 0},
{0x71, {{"SMULHd", 0},                  {"SMULHd", 0},                  {"", 0}                        }, 0},
{0x72, {{"PFHADDs", 0},                 {"PFHADDs", 0},                 {"", 0}                        }, 0},
{0x73, {{"PFHSUBs", 0},                 {"PFHSUBs", 0},                 {"", 0}                        }, 0},
{0x77, {{"PFADDSUBs", 0},               {"PFADDSUBs", 0},               {"", 0}                        }, 0},
};

e2k_oper elbrus_v4_long_opers [] =
{
{0x24, {{"", 0},                        {"FSCALEs", 0},                 {"", 0}                        }, 0},
{0x25, {{"", 0},                        {"FSCALEd", 0},                 {"", 0}                        }, 0},
{0x27, {{"", 0},                        {"FXSCALEsx", 0},               {"", 0}                        }, 0},
{0x30, {{"", 0},                        {"", 0},                        {"PFADDs", 0}                  }, 0},
{0x31, {{"", 0},                        {"", 0},                        {"PFADDd", 0}                  }, 0},
{0x32, {{"", 0},                        {"", 0},                        {"PFSUBs", 0}                  }, 0},
{0x33, {{"", 0},                        {"", 0},                        {"PFSUBd", 0}                  }, 0},
{0x38, {{"", 0},                        {"", 0},                        {"PFMULs", 0}                  }, 0},
{0x72, {{"", 0},                        {"", 0},                        {"PFHADDs", 0}                 }, 0},
{0x73, {{"", 0},                        {"", 0},                        {"PFHSUBs", 0}                 }, 0},
{0x77, {{"", 0},                        {"", 0},                        {"PFADDSUBs", 0}               }, 0},
};

e2k_oper elbrus_v5_long_opers [] =
{
{0x01, {{"", 0},                        {"", 0},                        {"STQ", 0}                     }, 0},
{0x26, {{"", 0},                        {"PMULLW", 0},                  {"", 0}                        }, 0},
{0x41, {{"LDQ", 0},                     {"", 0},                        {"LDQ", 0}                     }, 0},
{0x60, {{"", 0},                        {"ADDCd", 0},                   {"", 0}                        }, 0},
{0x61, {{"", 0},                        {"ADDCd_C", 0},                 {"", 0}                        }, 0},
{0x62, {{"", 0},                        {"SUBCd", 0},                   {"", 0}                        }, 0},
{0x63, {{"", 0},                        {"SUBCd_C", 0},                 {"", 0}                        }, 0},
{0x74, {{"GETFZs", 0},                  {"GETFZs", 0},                  {"GETFZs", 0}                  }, 0},
{0x75, {{"GETFZd", 0},                  {"GETFZd", 0},                  {"GETFZd", 0}                  }, 0},
};

e2k_oper elbrus_v6_long_opers [] =
{
{0x40, {{"PMRGP", 0},                   {"PMRGP", 0},                   {"", 0}                        }, 0},
{0x53, {{"IBRANCHD", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x54, {{"ICALLD", 0},                  {"", 0},                        {"", 0}                        }, 0},
};

e2k_oper elbrus_v3_long_ext1_opers [] =
{
{0x10, {{"PSRLW", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x11, {{"PSRLH", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x12, {{"PSRAW", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x13, {{"PSRAH", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x14, {{"PSLLW", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x15, {{"PSLLH", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x20, {{"PMINUW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x21, {{"PMINSW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x22, {{"PMAXUW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x23, {{"PMAXSW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x29, {{"PHADDH", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x2a, {{"PHADDW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x2b, {{"PHADDSH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x2d, {{"PHSUBH", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x2e, {{"PHSUBW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x2f, {{"PHSUBSH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x30, {{"PSIGNB", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x31, {{"PSIGNH", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x32, {{"PSIGNW", 0},                  {"", 0},                        {"", 0}                        }, 0},
};

e2k_oper elbrus_v4_long_ext1_opers [] =
{
{0x30, {{"", 0},                        {"", 0},                        {"FADDs", 0}                   }, 0},
{0x31, {{"", 0},                        {"", 0},                        {"FADDd", 0}                   }, 0},
{0x32, {{"", 0},                        {"", 0},                        {"FSUBs", 0}                   }, 0},
{0x33, {{"", 0},                        {"", 0},                        {"FSUBd", 0}                   }, 0},
{0x38, {{"", 0},                        {"", 0},                        {"FMULs", 0}                   }, 0},
{0x39, {{"", 0},                        {"", 0},                        {"FMULd", 0}                   }, 0},
};

e2k_oper elbrus_v5_long_ext1_opers [] =
{
{0x00, {{"QPSRLW", 0},                  {"QPSRLW", 0},                  {"", 0}                        }, 0},
{0x01, {{"QPSRLH", 0},                  {"QPSRLH", 0},                  {"", 0}                        }, 0},
{0x02, {{"QPSRAW", 0},                  {"QPSRAW", 0},                  {"", 0}                        }, 0},
{0x03, {{"QPSRAH", 0},                  {"QPSRAH", 0},                  {"", 0}                        }, 0},
{0x04, {{"QPSLLW", 0},                  {"QPSLLW", 0},                  {"", 0}                        }, 0},
{0x05, {{"QPSLLH", 0},                  {"QPSLLH", 0},                  {"", 0}                        }, 0},
{0x06, {{"QPSRLD", 0},                  {"QPSRLD", 0},                  {"", 0}                        }, 0},
{0x07, {{"QPSLLD", 0},                  {"QPSLLD", 0},                  {"", 0}                        }, 0},
{0x08, {{"QPAND", 0},                   {"QPAND", 0},                   {"", 0}                        }, 0},
{0x09, {{"QPANDN", 0},                  {"QPANDN", 0},                  {"", 0}                        }, 0},
{0x0a, {{"QPOR", 0},                    {"QPOR", 0},                    {"", 0}                        }, 0},
{0x0b, {{"QPXOR", 0},                   {"QPXOR", 0},                   {"", 0}                        }, 0},
{0x0c, {{"QPMINUW", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x0d, {{"QPMINSW", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x0e, {{"QPMAXUW", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x0f, {{"QPMAXSW", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x11, {{"", 0},                        {"", 0},                        {"STMQP", 0}                   }, 0},
{0x12, {{"", 0},                        {"", 0},                        {"STCSMQP", 0}                 }, 0},
{0x13, {{"", 0},                        {"", 0},                        {"STDSMQP", 0}                 }, 0},
{0x14, {{"", 0},                        {"", 0},                        {"STESMQP", 0}                 }, 0},
{0x15, {{"", 0},                        {"", 0},                        {"STFSMQP", 0}                 }, 0},
{0x16, {{"PSRCW", 0},                   {"PSRCW", 0},                   {"STGSMQP", 0}                 }, 0},
{0x17, {{"PSRCD", 0},                   {"PSRCD", 0},                   {"STSSMQP", 0}                 }, 0},
{0x18, {{"QPCMPEQD", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x19, {{"QPHADDH", 0},                 {"", 0},                        {"STGDMQP", 0}                 }, 0},
{0x1a, {{"QPHADDW", 0},                 {"", 0},                        {"STAPMQP", 0}                 }, 0},
{0x1b, {{"QPHADDSH", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x1c, {{"QPCMPGTD", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x1d, {{"QPHSUBH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x1e, {{"QPHSUBW", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x1f, {{"QPHSUBSH", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x20, {{"", 0},                        {"", 0},                        {"STAAQP", 0}                  }, 0},
{0x21, {{"", 0},                        {"", 0},                        {"STQP", 0}                    }, 0},
{0x22, {{"", 0},                        {"", 0},                        {"STCSQP", 0}                  }, 0},
{0x23, {{"", 0},                        {"", 0},                        {"STDSQP", 0}                  }, 0},
{0x24, {{"", 0},                        {"", 0},                        {"STESQP", 0}                  }, 0},
{0x25, {{"", 0},                        {"", 0},                        {"STFSQP", 0}                  }, 0},
{0x26, {{"QPSRCW", 0},                  {"QPSRCW", 0},                  {"STGSQP", 0}                  }, 0},
{0x27, {{"QPSRCD", 0},                  {"QPSRCD", 0},                  {"STSSQP", 0}                  }, 0},
{0x29, {{"", 0},                        {"", 0},                        {"STGDQP", 0}                  }, 0},
{0x2a, {{"", 0},                        {"", 0},                        {"STAPQP", 0}                  }, 0},
{0x2b, {{"", 0},                        {"", 0},                        {"STRQP", 0}                   }, 0},
{0x34, {{"QPMSK2SGNB", 0},              {"QPMSK2SGNB", 0},              {"", 0}                        }, 0},
{0x38, {{"QPSIGNB", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x39, {{"QPSIGNH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x3a, {{"QPSIGNW", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x3c, {{"QPSGN2MSKB", 0},              {"QPSGN2MSKB", 0},              {"", 0}                        }, 0},
{0x3d, {{"QPPACKDL", 0},                {"QPPACKDL", 0},                {"", 0}                        }, 0},
{0x3e, {{"QPSWITCHW", 0},               {"QPSWITCHW", 0},               {"", 0}                        }, 0},
{0x3f, {{"QPSWITCHD", 0},               {"QPSWITCHD", 0},               {"", 0}                        }, 0},
{0x40, {{"QPMINUB", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x41, {{"QPMINSH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x42, {{"QPMAXUB", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x43, {{"QPMAXSH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x44, {{"QPMINSB", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x45, {{"QPMINUH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x46, {{"QPMAXSB", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x47, {{"QPMAXUH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x48, {{"QPADDB", 0},                  {"QPACKSSHB", 0},               {"", 0}                        }, 0},
{0x49, {{"QPADDH", 0},                  {"QPACKUSHB", 0},               {"", 0}                        }, 0},
{0x4a, {{"QPADDSB", 0},                 {"QPACKSSWH", 0},               {"", 0}                        }, 0},
{0x4b, {{"QPADDSH", 0},                 {"QPACKUSWH", 0},               {"", 0}                        }, 0},
{0x4c, {{"QPADDUSB", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x4d, {{"QPADDUSH", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x4e, {{"QPADDW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x4f, {{"QPADDD", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x50, {{"QPSUBB", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x51, {{"QPSUBH", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x52, {{"QPSUBSB", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x53, {{"QPSUBSH", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x54, {{"QPSUBUSB", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x55, {{"QPSUBUSH", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x56, {{"QPSUBW", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x57, {{"QPSUBD", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x58, {{"QPCMPEQB", 0},                {"QPMULHH", 0},                 {"", 0}                        }, 0},
{0x59, {{"QPCMPEQH", 0},                {"QPMULLH", 0},                 {"", 0}                        }, 0},
{0x5a, {{"QPCMPEQW", 0},                {"QPMADDH", 0},                 {"", 0}                        }, 0},
{0x5b, {{"QPCMPGTB", 0},                {"QPMULHUH", 0},                {"", 0}                        }, 0},
{0x5c, {{"QPCMPGTH", 0},                {"QPSADBW", 0},                 {"", 0}                        }, 0},
{0x5d, {{"QPCMPGTW", 0},                {"QPMULUBHH", 0},               {"", 0}                        }, 0},
{0x5e, {{"QPAVGUSB", 0},                {"QPMULLW", 0},                 {"", 0}                        }, 0},
{0x5f, {{"QPAVGUSH", 0},                {"", 0},                        {"", 0}                        }, 0},
{0x60, {{"", 0},                        {"", 0},                        {"LDAAQP", 0}                  }, 0},
{0x61, {{"LDQP", 0},                    {"", 0},                        {"LDQP", 0}                    }, 0},
{0x62, {{"LDCSQP", 0},                  {"", 0},                        {"LDCSQP", 0}                  }, 0},
{0x63, {{"LDDSQP", 0},                  {"", 0},                        {"LDDSQP", 0}                  }, 0},
{0x64, {{"LDESQP", 0},                  {"", 0},                        {"LDESQP", 0}                  }, 0},
{0x65, {{"LDFSQP", 0},                  {"", 0},                        {"LDFSQP", 0}                  }, 0},
{0x66, {{"LDGSQP", 0},                  {"", 0},                        {"LDGSQP", 0}                  }, 0},
{0x67, {{"LDSSQP", 0},                  {"", 0},                        {"LDSSQP", 0}                  }, 0},
{0x68, {{"LDCUDQP", 0},                 {"QPMADDUBSH", 0},              {"LDCUDQP", 0}                 }, 0},
{0x69, {{"LDGDQP", 0},                  {"QPMULHRSH", 0},               {"LDGDQP", 0}                  }, 0},
{0x6a, {{"LDAPQP", 0},                  {"QPHMINPOSUH", 0},             {"LDAPQP", 0}                  }, 0},
{0x6b, {{"LDRQP", 0},                   {"QPMPSADBH", 0},               {"LDRQP", 0}                   }, 0},
{0x6c, {{"PUTTAGQP", 0},                {"PUTTAGQP", 0},                {"", 0}                        }, 0},
{0x6d, {{"QPTOQP", 0},                  {"QPTOQP", 0},                  {"", 0}                        }, 0},
{0x6e, {{"QPFSTOIFs", 0},               {"QPFSTOIFs", 0},               {"", 0}                        }, 0},
{0x6f, {{"QPFDTOIFd", 0},               {"QPFDTOIFd", 0},               {"", 0}                        }, 0},
{0x70, {{"QPFADDs", 0},                 {"QPFADDs", 0},                 {"QPFADDs", 0}                 }, 0},
{0x71, {{"QPFADDd", 0},                 {"QPFADDd", 0},                 {"QPFADDd", 0}                 }, 0},
{0x72, {{"QPFSUBs", 0},                 {"QPFSUBs", 0},                 {"QPFSUBs", 0}                 }, 0},
{0x73, {{"QPFSUBd", 0},                 {"QPFSUBd", 0},                 {"QPFSUBd", 0}                 }, 0},
{0x74, {{"QPFMINs", 0},                 {"QPFMINs", 0},                 {"", 0}                        }, 0},
{0x75, {{"QPFMINd", 0},                 {"QPFMINd", 0},                 {"", 0}                        }, 0},
{0x76, {{"QPFMAXs", 0},                 {"QPFMAXs", 0},                 {"", 0}                        }, 0},
{0x77, {{"QPFMAXd", 0},                 {"QPFMAXd", 0},                 {"", 0}                        }, 0},
{0x78, {{"QPFMULs", 0},                 {"QPFMULs", 0},                 {"QPFMULs", 0}                 }, 0},
{0x79, {{"QPFMULd", 0},                 {"QPFMULd", 0},                 {"QPFMULd", 0}                 }, 0},
{0x7a, {{"QPFCMPs", 0},                 {"QPFCMPs", 0},                 {"", 0}                        }, 0},
{0x7b, {{"QPFCMPd", 0},                 {"QPFCMPd", 0},                 {"", 0}                        }, 0},
{0x7c, {{"QPFHADDs", 0},                {"QPFHADDs", 0},                {"QPFHADDs", 0}                }, 0},
{0x7d, {{"QPFHSUBs", 0},                {"QPFHSUBs", 0},                {"QPFHSUBs", 0}                }, 0},
{0x7e, {{"QPFADDSUBs", 0},              {"QPFADDSUBs", 0},              {"QPFADDSUBs", 0}              }, 0},
{0x7f, {{"QPFADDSUBd", 0},              {"QPFADDSUBd", 0},              {"QPFADDSUBd", 0}              }, 0},
};

e2k_oper elbrus_v6_long_ext1_opers [] =
{
{0x25, {{"QPSRAD", 0},                  {"QPSRAD", 0},                  {"", 0}                        }, 0},
{0x28, {{"PCMPP", 0},                   {"", 0},                        {"", 0}                        }, 0},
{0x2c, {{"QPCMPP", 0},                  {"", 0},                        {"", 0}                        }, 0},
{0x33, {{"QPCHECK", 0},                 {"", 0},                        {"", 0}                        }, 0},
{0x35, {{"QPCEXT", 0},                  {"QPCEXT", 0},                  {"", 0}                        }, 0},
{0x60, {{"QPMRGP", 0},                  {"QPMRGP", 0},                  {"", 0}                        }, 0},
};

e2k_oper elbrus_v6_long_ext2_opers [] =
{
{0x00, {{"FMAs", 0},                    {"FMAs", 0},                    {"FMAs", 0}                    }, 0},
{0x01, {{"FMAd", 0},                    {"FMAd", 0},                    {"FMAd", 0}                    }, 0},
{0x02, {{"FMSs", 0},                    {"FMSs", 0},                    {"FMSs", 0}                    }, 0},
{0x03, {{"FMSd", 0},                    {"FMSd", 0},                    {"FMSd", 0}                    }, 0},
{0x04, {{"FNMAs", 0},                   {"FNMAs", 0},                   {"FNMAs", 0}                   }, 0},
{0x05, {{"FNMAd", 0},                   {"FNMAd", 0},                   {"FNMAd", 0}                   }, 0},
{0x06, {{"FNMSs", 0},                   {"FNMSs", 0},                   {"FNMSs", 0}                   }, 0},
{0x07, {{"FNMSd", 0},                   {"FNMSd", 0},                   {"FNMSd", 0}                   }, 0},
{0x08, {{"QPFMAs", 0},                  {"QPFMAs", 0},                  {"QPFMAs", 0}                  }, 0},
{0x09, {{"QPFMAd", 0},                  {"QPFMAd", 0},                  {"QPFMAd", 0}                  }, 0},
{0x0a, {{"QPFMSs", 0},                  {"QPFMSs", 0},                  {"QPFMSs", 0}                  }, 0},
{0x0b, {{"QPFMSd", 0},                  {"QPFMSd", 0},                  {"QPFMSd", 0}                  }, 0},
{0x0c, {{"QPFNMAs", 0},                 {"QPFNMAs", 0},                 {"QPFNMAs", 0}                 }, 0},
{0x0d, {{"QPFNMAd", 0},                 {"QPFNMAd", 0},                 {"QPFNMAd", 0}                 }, 0},
{0x0e, {{"QPFNMSs", 0},                 {"QPFNMSs", 0},                 {"QPFNMSs", 0}                 }, 0},
{0x0f, {{"QPFNMSd", 0},                 {"QPFNMSd", 0},                 {"QPFNMSd", 0}                 }, 0},
{0x10, {{"QPFMASs", 0},                 {"QPFMASs", 0},                 {"QPFMASs", 0}                 }, 0},
{0x11, {{"QPFMASd", 0},                 {"QPFMASd", 0},                 {"QPFMASd", 0}                 }, 0},
{0x12, {{"QPFMSAs", 0},                 {"QPFMSAs", 0},                 {"QPFMSAs", 0}                 }, 0},
{0x13, {{"QPFMSAd", 0},                 {"QPFMSAd", 0},                 {"QPFMSAd", 0}                 }, 0},
{0x14, {{"CLMULL", 0},                  {"CLMULL", 0},                  {"", 0}                        }, 0},
{0x15, {{"CLMULH", 0},                  {"CLMULH", 0},                  {"", 0}                        }, 0},
};

